# Generated by Django 4.0.4 on 2022-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_employeers',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
