# Generated by Django 4.0.4 on 2022-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMB', '0002_alter_register_employeers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_employeers',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
